MISSING_PENALTY = 10
INCORRECT_PENALTY = 5
CONFLICTING_PENALTY = 15
EXTRA_PENALTY = 3


class ScoringService:
    """
    Calculates the overall evaluation score and provides
    a detailed score breakdown based on the detected errors.
    """

    def calculate_score(self, report: dict) -> int:
        """
        Calculates the final evaluation score.

        Args:
            report: Evaluation report generated by the evaluator.

        Returns:
            The final score after applying all deductions.
        """

        breakdown = self.get_score_breakdown(report)

        return breakdown["final_score"]

    def get_score_breakdown(self, report: dict) -> dict:
        """
        Computes the score breakdown for each error category
        and returns the final evaluation score.

        Args:
            report: Evaluation report generated by the evaluator.

        Returns:
            A dictionary containing the score breakdown and
            the final evaluation score.
        """

        starting_score = 100

        missing_count = len(report["missing_information"])
        incorrect_count = len(report["incorrect_information"])
        conflicting_count = len(report["conflicting_information"])
        extra_count = len(report["extra_information"])

        missing_deduction = missing_count * MISSING_PENALTY
        incorrect_deduction = incorrect_count * INCORRECT_PENALTY
        conflicting_deduction = conflicting_count * CONFLICTING_PENALTY
        extra_deduction = extra_count * EXTRA_PENALTY

        final_score = (
            starting_score
            - missing_deduction
            - incorrect_deduction
            - conflicting_deduction
            - extra_deduction
        )

        final_score = max(final_score, 0)

        return {

            "starting_score": starting_score,

            "missing": {
                "count": missing_count,
                "penalty": MISSING_PENALTY,
                "deduction": missing_deduction
            },

            "incorrect": {
                "count": incorrect_count,
                "penalty": INCORRECT_PENALTY,
                "deduction": incorrect_deduction
            },

            "conflicting": {
                "count": conflicting_count,
                "penalty": CONFLICTING_PENALTY,
                "deduction": conflicting_deduction
            },

            "extra": {
                "count": extra_count,
                "penalty": EXTRA_PENALTY,
                "deduction": extra_deduction
            },

            "final_score": final_score
        }